apps/form-builder/src/server/actions/forms.ts

Created delete form server function

---

packages/internal-models/src/db/actions/Applicant.ts
packages/internal-models/src/db/models/Applicant.ts

- fix schema to actually export what it needs to
- add `deleteApplicant` server function
- #22

fixed applicant schema, added delete applicant server func

---

.github/ISSUE_TEMPLATE/admin-portal.md

Create template for issues meant for the admin portal project
N/A
N/A

create issue template for admin portal

---

apps/applicant-tracking/src/app/dashboard/page.tsx

- Created a folder in src called dashboard
- created page.tsx
- created dashboard page function
- #12 
Can we capitalize the p in page, or is it purposefully lowercase? 
- [ X] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings

Created dashboard folder, dashboard page, and dashboard page function

---

apps/form-builder/package.json
apps/form-builder/src/app/api/forms/[formId]/formSubmissions/route.ts
apps/form-builder/src/server/actions/formSubmissions.ts
package-lock.json

Closes #15 
Creates form submission ID and adds to form. 
#15

Created POST FormSubmission API

---

apps/form-builder/src/app/api/forms/route.ts
apps/form-builder/src/server/actions/forms.ts

this code makes a request to create a new form in the data base IF request meets specified guidelines
close #1, 
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings
- [x ] I have assigned reviewers to this PR 
close

form creator (issue #1)

---

apps/form-builder/src/app/forms/create/page.tsx

created initial version. Not complete
- #37

Create new form initial - needs to be completed -

---

apps/form-builder/src/app/api/forms/[formId]/formSubmissions/route.ts
package-lock.json
package.json

Function to get all form submissions created with success status code
- #20 
I had trouble getting it to work on my computer but I was having issues figuring out how to run the server so there I believe that was just user error but I'm not sure

function to get all form submissions created

---

apps/applicant-tracking/src/app/api/applicants/[applicantId]/route.ts

created a function that deletes member from database
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have assigned reviewers to this PR

23 delete applicant api endpoint

---

apps/applicant-tracking/src/app/applicants/page.tsx

I created an applicant list page. 
-  [X] My changes generate no new warnings

Made applicants page.

---

apps/applicant-tracking/src/app/applicants/[applicantId]/page.tsx

Wrote code that creates a single applicant page
Straight forward; returns h1 tag. Completed with help of Zavier
N/A

created single applicant page

---

packages/internal-models/src/db/actions/Applicant.ts

I made the single applicant server function

17 get single applicant server function

---

packages/internal-models/src/db/actions/Applicant.ts

get all applicants server function

---

apps/applicant-tracking/src/services/api/applicant.ts
apps/applicant-tracking/src/services/index.ts
apps/applicant-tracking/src/utils/constants/urls.ts
apps/applicant-tracking/src/utils/errors/validation-error.ts
packages/internal-models/src/db/models/Applicant.ts
packages/internal-models/src/db/models/index.ts
packages/internal-models/src/types/applicant.ts
packages/internal-models/src/types/index.ts

update applicant type and schema and add applicant api service

---

apps/form-builder/src/app/api/forms/[formId]/route.ts
apps/form-builder/src/server/actions/forms.ts

Form Delete API

---

apps/admin-portal/src/app/members/[memberId]/page.tsx
apps/admin-portal/src/app/members/page.tsx

added a members list page and individual members page

created members list page and member specific page

---

apps/admin-portal/src/components/Event/index.tsx

Added an interface with variables that were used in the following component.
#50
if insert commands in the beginning are needed

Created an event component

---

apps/admin-portal/src/components/Member/index.tsx

Created the Member component, which currently takes props for name, year, and project.
#45

Created Member component

---

apps/admin-portal/src/components/Project/index.tsx

Created a folder called "Project" withing the "components" folder. Then put a file "index.tsx" within "Project". Within "index.tsx", I created an interface to hold project name, status, and members. I then created a component to print the values held within the interface.

Made Project Page

---

apps/admin-portal/src/app/events/page.tsx

- Adds an Event Creation page 
- #49 
-none

Created the Event Creation Page

---

packages/internal-models/src/db/actions/Applicant.ts

I created a server function that updates the applicant interview information.
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works
- [X ] I have assigned reviewers to this PR

create server func to update applicant interview info

---

apps/admin-portal/src/components/NavigationDrawer/NavigationDrawerItem/index.tsx
apps/admin-portal/src/components/NavigationDrawer/index.tsx

Creating the navigation drawer component. Added files, created index.tsx implementation for NavigationDrawer and index.tsx components for NavigationDrawerItem. 
#46 
N/A

46 navigation bar comp

---

apps/admin-portal/src/components/pagelink/index.tsx

I have created a page link component to be later added to the dashboard. These page links take a url, page title, and page description. The information will show up in a box. When the box is clicked on, you will be routed to the link destination.
I am not sure as to what theme we were going for so I left the color as the primary.main color. I would be happy to change the theme and look of the box if requested to. Also, I pushed the file then realized I forgot to delete something, so I made the change then pushed it again. I am not sure how to change the first push so that I am only pushing one file, or how to delete the first push.

87 efisk create page link component for dashboard

---

apps/admin-portal/src/app/projects/page.tsx
package-lock.json
package.json

Added project folder and project List page
Create Project list page #40

Added projects folder and page

---

apps/form-builder/src/app/forms/formSubmissions/[formSubmissionId]/page.tsx
package-lock.json

Example description
- #137 
Did I do this right?

Made the page

---

apps/applicant-tracking/package.json
apps/applicant-tracking/src/components/AppBar/AppBarItem/index.tsx
apps/applicant-tracking/src/components/NavigationDrawer/AppBar/index.tsx
apps/applicant-tracking/src/components/NavigationDrawer/index.tsx
package-lock.json

created app bar component
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have assigned reviewers to this PR

41 create appbar component

---

apps/admin-portal/src/app/layout.tsx
apps/admin-portal/src/app/page.tsx
apps/admin-portal/src/components/Appbar/index.tsx
apps/admin-portal/src/components/Member/index.tsx
apps/admin-portal/src/components/NavigationDrawer/NavigationDrawerItem/index.tsx
apps/admin-portal/src/components/Project/index.tsx
apps/admin-portal/src/components/pagelink/index.tsx
package-lock.json

make sure MUI pages use client

---

apps/admin-portal/src/components/NavigationDrawer/index.tsx

Linking pages from navigation drawer
98
#98

98-AP Create link to pages

---

apps/admin-portal/src/components/NavigationDrawer/index.tsx
package-lock.json

fix broken links

---

apps/applicant-tracking/src/services/api/applicant.ts

created getAllActionable applicants frontend service

---

packages/internal-models/src/db/actions/Applicant.ts

<Created get applicants by status server function>

wrote get applicants by statuses server funciton

---

apps/applicant-tracking/src/components/TermSelector/index.tsx

Created a button to display the term. It is currently set to "Spring 2024". Arrows added to select between terms.
Test code
```
import React from 'react';
import TermSelector from '@/components/TermSelector';
export default function DashboardPage() {
//  return <h1>Dashboard page</h1>;
return (
<div>
<TermSelector />
</div>
);
}
```

Term Selector Button

---

apps/applicant-tracking/src/components/DashboardList/index.tsx

//Creates a component that will be a list of all applicants who need some sort of action taken.

dashbboard list component

---

apps/applicant-tracking/src/components/ApplicantList/index.tsx

This adds an `ApplicantList` component for use on the applicants page
- #145 
```tsx
import ApplicantList from '@/components/ApplicantList';
import { ApplicantResponse } from '@hack4impact-utk/internal-models';
const applicants: any[] = [
{
firstName: 'John',
lastName: 'Doe',
netid: 'jdoe',
term: 'Fall 2021',
referrer: 'Jane Doe',
major: 'Computer Science',
expectedGraduation: 'Spring 2023',
status: 'Pending Review',
},
{
firstName: 'Jane',
lastName: 'Doe',
netid: 'jadoe',
term: 'Fall 2021',
referrer: 'John Doe',
major: 'Computer Science',
expectedGraduation: 'Spring 2023',
status: 'Pending Review',
},
{
firstName: 'Alice',
lastName: 'Smith',
netid: 'asmith',
term: 'Fall 2021',
referrer: 'Bob Smith',
major: 'Computer Science',
expectedGraduation: 'Spring 2023',
status: 'Pending Review', …
```

Create Applicant List Component

---

packages/internal-models/src/db/actions/Applicant.ts

created an update applicant status function
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] My changes generate no new warnings
- [x ] I have assigned reviewers to this PR

created update applicant status function

---

apps/form-builder/src/app/forms/[formId]/page.tsx
apps/form-builder/src/components/TextOptions/index.tsx

Created switch component.
- #141 
Should I add or change anything?

Created component

---

apps/form-builder/src/app/api/forms/route.ts

Had to remake the branch to fix some issues with my local copy of the repo, just added back in what I did before
-#3

added Get all forms api endpoint

---

apps/form-builder/src/app/forms/page.tsx
apps/form-builder/src/components/FormsTable/index.tsx

Created forms table component showing the title, responder type, anonymity, response count, and date last updated for each form. I then put this component on the forms page.
-#130

created form table component then added it to forms page.

---

apps/form-builder/src/components/NumericOptions.tsx

Created two text fields minimum and maximum value, as well as a switch that asks if decimals are allowed.
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works

140 create numericoptions component

---

apps/form-builder/src/components/FormsTable/index.tsx

Added filters/sorting and a search bar to the forms table page
#134 
#133 
N/A

134 add filters to forms page

---

apps/form-builder/src/components/FormsTable/index.tsx

Made forms table rows clickable and link to that form's page
#132 
- How much should I be commenting? I think most of what I used is more or less self explanatory or simple but should I be adding more comments?

added clickable rows to forms table

---

apps/form-builder/src/app/forms/page.tsx
package-lock.json

New Form button added to `src/app/forms/page.tsx`
#131

131 create new form button

---

packages/internal-models/src/db/actions/Teams.ts

created new file Teams.ts, then created async function getAllTeams()
#164

Added async function to return all teams.

---

packages/internal-models/src/db/actions/Members.ts

Added getAllMembers() function. Not able to test yet so lmk if I need to change anything, it's pretty barebones.
- #161

Added getAllMembers function

---

packages/internal-models/src/db/actions/Projects.ts

Create a server function that retrieves all the projects from the database.
#162

162 Create Server Function for Projects

---

apps/admin-portal/src/components/Member/index.tsx

Styled the member card to feature a picture, as well as clickable Github/LinkedIn links
If no picture is provided, the H4I logo is inserted instead. This can easily be changed if needed.
Screenshot of four tests below. The right side tests the optional pronoun feature and the bottom half tests the image feature.
Image datatype in props and the Image tag may need to be changed later to properly function with the images in the database.
BTW the super long link is a URI for the H4I logo used when no image is provided.
- #171

Re-styled member component with card design

---

apps/admin-portal/src/app/teams/page.tsx

add teams page for admin-portal

---

apps/form-builder/src/app/forms/[formId]/page.tsx
apps/form-builder/src/components/FormSubmissions/FileUploadQuestionAnalytics.tsx

Created component that displays form question's file upload responses
- #58 
Is this okay?

58 create fileuploadquestionanalytics component 1

---

apps/form-builder/src/components/FormSubmissions/PieChartAnalytics.tsx

This creates a pie chart that shows 1.) If the answers are given options 2.) displays them by choice or other
This code was put on page.tsx to test
import PieChartAnalytics from '@/components/FormSubmissions/PieChartAnalytics';
const sampleChoices = [
'Apple',
'Banana',
'Orange',
'Grapes',
'Mango',
'Pineapple',
];
const sampleAnswers = [
['Apple', 'Banana', 'Orange', 'Grapes'],
['Banana', 'Orange', 'Grapes'],
['Orange', 'Grapes'],
['Grapes'],
['Mango', 'Pineapple', 'Oeange'],
['Pineapple', 'Strawberry'],
['Pineapple'],
['Manog'],
['Apple', 'Mango', 'Pineapple', 'Grapes'],
['Banana', 'Orange', 'Grapes', 'Watermelon'],
['Grapes', 'Mango', 'Pineapple', 'Strawberry', 'Banana'],
];
export default function Home() {
return PieChartAnalytics choices={sampleChoices} answers={sampleAnswers} ;
}
- …

71 create piechartanalytics component

---

packages/internal-models/src/db/actions/Applicant.ts

Included a a server function that updates the decision for an applicant
#187

Add makeDecisionForApplicant function to Applicant.ts

---

apps/applicant-tracking/src/app/applicants/applications/page.tsx
package-lock.json

Created a file for applications under applicants and created an applicants page under said file
The stuff I put in was relatively simple so I'd be suprised if there was any issues
- [ check] My code follows the style guidelines of this project
- [check ] I have performed a self-review of my code
- [check ] I have commented my code, particularly in hard-to-understand areas
- [check ] I have made corresponding changes to the documentation
- [ check] My changes generate no new warnings
- [check ] I have added tests that prove my fix is effective or that my feature works
- [check ] I have assigned reviewers to this PR

Created Applicants Page

---

apps/applicant-tracking/src/app/applicants/meetings/page.tsx

I added a meetings page to the applicant tracking system in order to learn the file tree and how everything works.
- #233 
None!

Created meetings page

---

apps/applicant-tracking/src/app/applicants/applications/page.tsx
apps/applicant-tracking/src/app/applicants/page.tsx
apps/applicant-tracking/src/components/LBPTeamsButton/index.tsx

I created a LBP teams button using the notes from workshop. I made the changes by creating a folder in components called LBPTeamsButton and made index.tsx where I wrote my code.
Check if my code is working and it is doing what it is supposed to do
functionality to not work as expected)
- [1] My code follows the style guidelines of this project
- [1] I have performed a self-review of my code
- [1] I have commented my code, particularly in hard-to-understand areas
- [1] I have made corresponding changes to the documentation
- [1] My changes generate no new warnings
- [1] I have added tests that prove my fix is effective or that my feature works
- [1] I have assigned reviewers to this PR

commiting my button

---

apps/applicant-tracking/src/app/applicants/history/page.tsx

Added history page in the applicants folder.
#234

Added history page in applicants folder.

---

apps/applicant-tracking/package.json
apps/applicant-tracking/src/app/applicants/[applicantId]/page.tsx
apps/applicant-tracking/src/app/applicants/applications/page.tsx
apps/applicant-tracking/src/components/ApplicantStylePage/applicantpage.js
package-lock.json

I styled the applicant page which includes the header, bar with name, date, year, major and status.
Design of the page, I was confused because It wasn't mentioned for me to create a filters page so I just created name, date, year, etc which was included in the instructions.
- [1] My code follows the style guidelines of this project
- [1] I have performed a self-review of my code
- [1] I have commented my code, particularly in hard-to-understand areas
- [1] I have made corresponding changes to the documentation
- [1] My changes generate no new warnings
- [1] I have added tests that prove my fix is effective or that my feature works
- [1] I have assigned reviewers to this PR

Applicant style page

---

apps/applicant-tracking/package.json
apps/applicant-tracking/src/app/applicants/page.tsx
apps/applicant-tracking/src/components/HistoryButton/index.tsx
package-lock.json

I made a folder called "HistoryButton" and made a file in that called "index.tsx" which is where I made the button function. Then in the "applicants" folder I edited a file called "page.tsx" to actually make the button visible in the page when it is opened.
#1 : Had some trouble committing things
Not sure if this required a documentation update so left it on in the "Type of change"

HistoryButton in Applications page

---

apps/applicant-tracking/src/components/ApplicantDetail/index.tsx

Detailed view of applicants that includes name, net id, term, number of no shows, and notes.
`import React from 'react';
import ApplicantDetail from '@/components/ApplicantDetail';
import { ApplicantResponse } from '@hack4impact-utk/internal-models';
const applicant: ApplicantResponse = {
_id: '233423',
firstName: 'Zavier',
lastName: 'miller',
status: 'Pending Review',
statusUpdatedAt: new Date(),
noShowCount: 2,
term: 'Fall 2024',
netid: 'zasvier',
notes: 'wants to join LBP',
};
export default function ApplicantsPage() {
return <ApplicantDetail applicant={applicant} />;
}
`

created applicant detail

---

apps/applicant-tracking/src/app/applicants/page.tsx
apps/applicant-tracking/src/components/MeetingsButton/index.tsx

Creating Meetings Button

---

apps/applicant-tracking/src/components/HistoryRightFilter/index.tsx

created right history filter

---

apps/applicant-tracking/src/app/applicants/page.tsx

Styling applicants page with title, image holder, and orange line.

Style applicant tracking page

---

apps/applicant-tracking/src/app/applicants/applications/page.tsx
apps/applicant-tracking/src/app/applicants/page.tsx

Small updates

---

apps/applicant-tracking/src/components/ApplicantsButton/index.tsx

Made applicants button with functionality

---

apps/applicant-tracking/src/components/RecentFilter.tsx
package-lock.json
package.json

made updates

---

apps/applicant-tracking/src/components/HistoryButton/index.tsx

Functionality for history button added
Added functionality to make history button send user to new page
#273

History Button Functionality

---

apps/applicant-tracking/src/app/applicants/[applicantId]/page.tsx
apps/applicant-tracking/src/components/ApplicantInfoPage/index.tsx

Added styling to the applicant info page and also added it to the list of pages that are available on the website.

Issue #269: Style Applicant Info Page Finished

---

apps/applicant-tracking/src/app/applicants/calendar/page.tsx
apps/applicant-tracking/src/components/CalendarButton/index.tsx

Calendar Button Implementation

---

apps/applicant-tracking/src/app/applicants/page.tsx
apps/applicant-tracking/src/components/ApplicantsButton/index.tsx
apps/applicant-tracking/src/components/HistoryButton/index.tsx
apps/applicant-tracking/src/components/LBPTeamsButton/index.tsx
apps/applicant-tracking/src/components/MeetingsButton/index.tsx

Added the Applicants, LBP Teams, Meetings, and History buttons to the Applicants page
#277

finished issue #277 Add Home Buttons

---

apps/form-builder/src/app/forms/page.tsx

- #272 
Forms and the divider are attached somehow? I wanted to move forms down a bit more, I don't remember the exact weirdness that started to happen just weirdness.

Task Style forms page

---

apps/form-builder/src/components/FormTabs/index.tsx

I added the form settings component to the settings tab in the form.
#151 
My code works as expected. It correctly adds the form settings component to the settings tab but there is a highlighted piece of text in the code that suggests is an error. I don't know what the error is because the form looks fine so if anyone can review and let me know where I might be going wrong, that'd be greatly appreciated.

151 add form settings component to settings tab

---

apps/applicant-tracking/src/components/ApplicationBar/index.tsx

Created application bar
- #287

Created application bar

---

apps/applicant-tracking/src/app/api/applicants/[applicantId]/route.ts
apps/applicant-tracking/src/app/api/applicants/route.ts
packages/internal-models/src/db/actions/Applicant.ts
packages/internal-models/src/db/models/Applicant.ts
packages/internal-models/src/types/onboarding/roleOnboarding.ts
packages/internal-models/src/types/project.ts
packages/internal-models/src/types/team.ts

Implemented the GET API call. Some of the mongoose models had broken imports so I fixed those, and some of the zod types had dependency loops causing a crash whenever a call was made. They were all related to the "team" models so I just commented out the lines in question until functionality for the team API is implemented.
#304 Create a GET Applicant API
N/A

Created GET Request

---

apps/form-builder/src/components/FormSubmissions/RankedChoiceAnalytics/rankedchoiceanalytics.tsx
package-lock.json

- #74 
its saying i need to check the env.local file, not sure where to find it or what it does tbh
- x New feature (non-breaking change which adds functionality)

Add stacked bar graph judah

---

apps/form-builder/src/components/FormsTable/index.tsx
package-lock.json

Added delete button, which isn't connected to backend yet, turned form title into a button that opens the form, un-highlights
a clicked row after clicking again somewhere else, truncated form title to look better
- #316 
Deleted form gets added after refreshing. I'm assuming this is because the form is still in the database
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have assigned reviewers to this PR

Updated grid styling

---

apps/applicant-tracking/src/app/api/applicants/[applicantId]/route.ts
packages/internal-models/src/db/actions/Applicant.ts
packages/internal-models/src/types/term.ts

Created PUT applicant API method and fixed Term zod type.
#303 Create PUT Applicant API
N/A

Created PUT API Method
